# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: LiusSyliusConektaPlugin:Greeting:staticallyGreet
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: LiusSyliusConektaPlugin:Greeting:dynamicallyGreet
        name: ~

sylius_checkout_override_complete:
    path: /checkout/override_complete
    methods: PUT
    defaults:
        _controller: LiusSyliusConektaPlugin:Checkout:complete
        name: ~
